version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: "npm start"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
    command: "npm test"
    entrypoint: ["sh", "-c", "npm install && npm test"]
    depends_on:
      - app

  release:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    entrypoint: ["sh", "-c", "npm install && npm run build"]
    depends_on:
      - tests

